# azure-pipelines.yml

parameters:
  - name: "testplan"
    type: string
    default: "CT-1276"

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  # It's a good practice to define the Python version as a variable
  python.version: '3.12.3'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    mkdir -p allure-results
    pytest --alluredir=allure-results ./test_examples.py
  displayName: 'Run Pytest and Upload to Xray Cloud'
  env:
    # Expose Azure DevOps secret variables as environment variables for the script
    XRAY_BASE_URL: $(XRAY_BASE_URL)
    XRAY_CLIENT_ID: $(XRAY_CLIENT_ID)
    XRAY_CLIENT_SECRET: $(XRAY_CLIENT_SECRET)

# Note: To make this pipeline functional, you need to configure the following
# secret variables in your Azure DevOps project settings (under Pipelines -> Library):
#   - XRAY_BASE_URL: Your Xray Cloud instance URL (e.g., https://xray.cloud.getxray.app)
#   - XRAY_CLIENT_ID: Your Xray API Client ID
#   - XRAY_CLIENT_SECRET: Your Xray API Client Secret
# These variables will be securely injected into the pipeline at runtime.

- bash: |
    set -x
    # Package Allure results
    zip -r allure-results.zip allure-results

    # Authenticate and get token
    export token=$(curl -H "Content-Type: application/json" -X POST --data "{ \"client_id\": \"$(XRAY_CLIENT_ID)\",\"client_secret\": \"$(XRAY_CLIENT_SECRET)\" }" "$(XRAY_BASE_URL)/api/v2/authenticate"| tr -d '"')

    # Import Allure results to Xray
    curl -X POST -H "Content-Type: application/zip" -H "Authorization: Bearer $token" --data @"allure-results.zip" "$(XRAY_BASE_URL)/api/v2/import/execution/allure?projectKey=CT&testPlanKey=${{ parameters.testplan }}"
  displayName: 'Package and Import Allure Results to Xray'
  env:
    # Expose Azure DevOps secret variables as environment variables for the script
    XRAY_BASE_URL: $(XRAY_BASE_URL)
    XRAY_CLIENT_ID: $(XRAY_CLIENT_ID)
    XRAY_CLIENT_SECRET: $(XRAY_CLIENT_SECRET)
  condition: always()
